author = Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2024-07-17
description = Create a html file showing svg plots
tags = C88
min-version = 2024a
public = gp2html
help = gp2html_help.md
sample-script = gp2html_sample.inp
